target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'MultiPlatformLibrary', :path => '../shared'
  pod 'MultiPlatformLibraryUnits',
    :git => 'https://github.com/icerockdev/moko-units.git', :tag => 'release/0.8.0'
end